/**
 * Single source of truth for every environment-specific value on the site.
 * Edit here; nothing below this file should hardcode a URL, handle or address.
 */

export interface SiteConfig {
  /** Absolute origin, no trailing slash. Used for canonical, OG and sitemap URLs. */
  readonly url: string
  readonly name: string
  readonly legalName: string
  readonly formerName: string
  readonly email: string
  readonly foundingLocation: string
  readonly foundingCountry: string
  /** Path under /public. Combined with `url` to produce an absolute og:image. */
  readonly ogImage: string
  readonly ogImageWidth: number
  readonly ogImageHeight: number
  /** Square brand mark for the nav. Rendered at `logoImageSize` CSS pixels. */
  readonly logoImage: string
  readonly logoImageSize: number
  readonly social: {
    readonly github: string
    readonly linkedin: string
  }
}

export const site: SiteConfig = {
  url: 'https://wefaber.net',
  name: 'WeFaber',
  legalName: 'WeFaber',
  formerName: 'Itica',
  email: 'hola@wefaber.net',
  foundingLocation: 'Montevideo',
  foundingCountry: 'UY',
  ogImage: '/og-image.png',
  ogImageWidth: 1200,
  ogImageHeight: 630,
  // 128px source rather than favicon.png (512px): same art, a sixth of the bytes
  // for a mark this small. Both are generated by `bun run assets`.
  logoImage: '/logo-mark.png',
  logoImageSize: 24,
  social: {
    github: 'https://github.com/wefaber',
    linkedin: 'https://www.linkedin.com/company/wefaber-net',
  },
}

/** Joins a root-relative path onto the site origin. */
export function absoluteUrl(path: string): string {
  return `${site.url}${path.startsWith('/') ? path : `/${path}`}`
}
